### ISSUE TITLE
Enable google maps api within embed api

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/stats4sd-resources-report#14]
The embed api used to integrate analytics charts is mostly a wrapper around the charts api, however it doesn't expose all methods (such as defining a google maps api key). During the time of embed api creation this was not a requirement, and has not actively been maintained to change this now that google maps does require keys. 

See issue: https://stackoverflow.com/questions/39637722/set-api-key-with-embed-api-google-analytics

As such additional script import is required to expose full functionality. This has been done in 8a3ef25ffe14d4cc2b3b4740ed6e73027e9dcac1. There are two scripts to import, one is included in `index.html` and the second is loaded dynamically on `googleAnalyticsService.vue` mount. This is because `process.env` is not available to the index.

This still leave a problem as the component is mounted multiple times on page change, and flags a potential error. A couple different ways to fix this might be:

- Add a check method to mount to see if it has already been loaded
- Refactor the service to only ever mount once (like an injected service/factory/provider)
- Find a way to import into index.html (likely exposing key, but could restrict it within google cloud)

**Comment by KingMike100** [comment]
The issue of the script being added multiple times as the component is mounted multiple times has been resolved. I have used the first approach of adding a check before the script is loaded as you can see in 0f1f826

**Comment by chrismclarke** [comment]
Nice solution, closing
